### ISSUE TITLE
Either counting tagged projects or displaying projects with a tag is broken

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/larp_library#104]
At the moment there are some tags on the front page that show a number of games (next to the tag in parenthesis) that does not match the number of games displayed when you click on the tag to show all games with that tag. 

The most obvious one would be "modern" which claims to have "1 project" but shows zero games if you click on it. There are others that are wrong, including "scene based" (shows "2 projects" on the front page, but only one when clicked) and "slice-of-life" (shows "3 projects" on the front page and only one if clicked). I have not done an exhaustive survey, so there are probably others as well.

**Comment by nbudin** [comment]
This turned out to be an issue with the data in Elasticsearch not being properly updated when things changed in the Postgres database.  I've fixed that, and manually updated the data in Elasticsearch, so things should be all good going forward.
