### ISSUE TITLE
LARP Library gives a JSON error when trying to load on iOS 14.5.1

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/larp_library#246]
I get a "JSON Parse error: Unrecognized token '<'" message when trying to load the LARP Library on my iPad.

**Comment by nbudin** [comment]
Hey Jeff, I think both this and the Intercon T/U site error you mentioned might have been because of a widespread outage last night that affected Heroku.  Is it still happening?

**Comment by diewald** [comment]
Additional notes:

1. The failures are on my iPad Pro, which isn't that old.
2. The failures continue after clearing the cache and history.
3. The websites work on my iPhone 8 Plus, also running iOS 14.5.1.

I'm going to update to 14.6, but it's still a concern.

**Comment by nbudin** [comment]
I also just tried it on my own iPad mini running 14.4 and my iPhone 12 mini running 14.6, and things seem fine on both of those.

The `JSON Parse error: Unrecognized token '<'` usually means we returned a server-side error page when the client was expecting JSON.  Looking in the server logs, I don't see anything super obvious for this.  If you have time and inclination, it'd be great if you could connect the iPad Pro to a Mac using a lightning cable and use Safari's developer tools to see if you can get ahold of the error response via the Network tab there, but I understand that's a lot to ask.

**Comment by diewald** [comment]
How's this? I'm available at 978-771-8693 if you want me to poke at other things, or poke at specific things on these pages, as I've never used the Safari developer tools before.

<img width="1440" alt="Screen Shot 2021-06-08 at 4 53 44 PM" src="https://user-images.githubusercontent.com/6187336/121256338-70dc8e80-c87a-11eb-9a51-00bda39fab9b.png">
<img width="1440" alt="Screen Shot 2021-06-08 at 4 53 26 PM" src="https://user-images.githubusercontent.com/6187336/121256345-72a65200-c87a-11eb-945b-64f5ec205bc9.png">

**Comment by diewald** [comment]
Also found this:

<img width="718" alt="Screen Shot 2021-06-08 at 4 59 42 PM" src="https://user-images.githubusercontent.com/6187336/121256863-02e49700-c87b-11eb-9d30-33512073c1c2.png">

**Comment by nbudin** [comment]
Super helpful, thanks!  Because it's a HTTP 422, I'm thinking this is an issue with CSRF authenticity tokens.  But, I would have thought clearing your cookies would have fixed that - basically, if you end up with an outdated authenticity token in your session cookie, clearing it should get Rails to generate a new one and put that in your cookies instead.  So I'm not totally sure why clearing didn't fix it for you.

I think the webpack:// errors aren't a real issue - it's the Safari developer tools seeing the source map attached to the JS and trying to pull a copy of it from your local webpack server, which doesn't actually exist.  It won't cause a problem in actual use, it'll just try and fail to get the source code in the developer tools if those are open.

**Comment by diewald** [comment]
Glad to help! Will report back what I find.

**Comment by nbudin** [comment]
(I think ultimately the solution  to this is going to be something like: we can't 100% prevent this from happening to people, but we can make the app behave better when it does.  Ideally, it could try to manually refresh the token itself.  Less ideally, it could display a message telling people to click this button to try logging out and back in.)

**Comment by diewald** [comment]
Updated to 14.6. Same problematic results, even after clearing history. Also same after clearing history and rebooting. No joy.

It shouldn't matter, but I'm using Google to provide the links, rather than trying to type them in.

**Comment by nbudin** [comment]
Blah, sorry!  I can't work on it right now but when I can, I'll see if I can get something more decent to happen when there's an invalid aurhenticity token.

**Comment by diewald** [comment]
No problem. Let me know when you want to test things out.

**Comment by nbudin** [comment]
In case you don't see it in Slack: I've deployed an experimental change to the server to handle CSRF token errors differently.  Let me know if it fixes things for you!

**Comment by diewald** [comment]
Sorry, I've had two rough migraine days in a row. The LARP Library works on my iPad, now at 14.6! Great work!

**Comment by nbudin** [comment]
Thanks!  Going to keep that fix in place and close this, in that case.

I actually don't think the issue you're experiencing in Intercode on that iPad can be the same issue, weirdly.  After reading through the code, it seems like we worked around the CSRF token stuff there in a different way that should mean that for read-only requests (like viewing a page) we don't even bother looking at the CSRF token.

If you wouldn't mind doing the same thing with Safari on an Intercon site, I'd super appreciate that!  But no rush - I'm about to be off the grid camping for a week, so I wouldn't really be able to do anything about it this week anyway.
