### ISSUE TITLE
link in brand description on the brands list does not work

### ISSUE THREAD

**Issue by valleyviolet** [neinteractiveliterature/larp_library#956]
On the brands page (https://library.interactiveliterature.org/brands) if I go to my listing ("Eva Schiffer") there is a link in my description that's meant to go to my homepage. If I click the link it instead goes to “https://library.interactiveliterature.org/brands/https://www.digitalchangeling.com/design/index.html”. If I go to my brand page (https://library.interactiveliterature.org/brands/eva-schiffer) the link works as expected.

**Comment by nbudin** [comment]
I'm not sure exactly how this happened, but it looks like a library upgrade implicitly fixed this in the meantime since it was reported.
